zookeeper:
  image: samsara/zookeeper
  container_name: zookeeper
  expose:
    - "2181"
    - "15001"
  environment:
    ZK_SERVER_ID: 1

kafka1:
  image: samsara/kafka
  container_name: kafka1
  expose:
    - "9092"
    - "15002"
  links:
    - zookeeper
  environment:
    KAFKA_BROKER_ID: 1

kafka2:
  image: samsara/kafka
  container_name: kafka2
  expose:
    - "9093"
    - "15003"
  links:
    - zookeeper
  environment:
    KAFKA_BROKER_ID: 2
    KAFKA_BROKER_PORT: 9093

kafka3:
  image: samsara/kafka
  container_name: kafka3
  expose:
    - "9094"
    - "15004"
  links:
    - zookeeper
  environment:
    KAFKA_BROKER_ID: 3
    KAFKA_BROKER_PORT: 9094

schemaregistry:
  build: schema-registry
  container_name: schemaregistry
  environment:
    SCHEMA_REGISTRY_DEBUG: "true"
  expose:
    - "8081"
  links:
    - zookeeper
    - kafka1
    - kafka2
    - kafka3

kafkarestproxy:
  build: kafka-rest-proxy
  container_name: kafkarestproxy
  expose:
    - "8082"
  links:
    - zookeeper
    - schemaregistry

